server:
  port: 8081

spring:
  application:
    name: board-backend

  datasource:
    url: jdbc:mysql://localhost:8080/boarddb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

# Gemini API Key (독립된 최상위 설정)
gemini:
  api:
    key: ${GEMINI_API_KEY:YOUR_GEMINI_API_KEY} # 하드코딩된 실제 키 값 삭제